name: growit
version: 1.0.0+1
publish_to: none
description: A new HRMS project employee dashboad.
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  intl: ^0.17.0
  get: 4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^5.1.0
  flutter_advanced_avatar: ^1.5.0
  carousel_slider: ^4.2.1
  entry: ^1.0.0
  calendar_view: ^1.2.0
  flutter_face_api: ^5.2.1
  google_mlkit_face_detection: ^0.11.0
  image_picker: ^1.1.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/splashhr.png
  android_12:
    color: "#ffffff"
    image: assets/splashhr.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icons/


