// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMUyUSGSVbd29DPgXjY1VUHWylEOdG14',
    appId: '1:483329949094:android:f73f17f73533e07fada367',
    messagingSenderId: '483329949094',
    projectId: 'eprovide-fa8a0',
    storageBucket: 'eprovide-fa8a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN7lw16mTfMwxPp9oOmgxQhfYzgrTUsBo',
    appId: '1:483329949094:ios:b356c90ca7d7755cada367',
    messagingSenderId: '483329949094',
    projectId: 'eprovide-fa8a0',
    storageBucket: 'eprovide-fa8a0.appspot.com',
    androidClientId:
        '483329949094-4eimij4k0b769qf8eatvmain3j4sje1m.apps.googleusercontent.com',
    iosClientId:
        '483329949094-i7k0qprsjttvg8tkdkplharisds83q0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.growit',
  );
}
